blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions (PT/ES)
    url: https://github.com/zeluizr/vtex-catalog-cloner/discussions
    about: "Perguntas, ideias e discussões gerais sobre o vtex-snap / Preguntas, ideas y discusiones generales sobre vtex-snap"
