name: Solicitud de Funcionalidad
description: Sugiere una nueva funcionalidad para vtex-snap
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema que resuelve
      description: ¿Qué problema o limitación actual resolvería esta funcionalidad?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción de la funcionalidad
      description: Describa la solución que le gustaría ver implementada.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: ¿Ha intentado alguna alternativa o solución temporal?
